# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - arch-tom

on:
  push:
    branches:
      - arch
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5f945d64f21647199f533800e072fc41 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b1e04b090b904d12bd8886c5eef6f458 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_5f945d64f21647199f533800e072fc41 }}/archtom:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'arch-tom'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_09b3d643dda14be5875beb26afe510c2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5f945d64f21647199f533800e072fc41 }}/archtom:${{ github.sha }}'